-- Set the colorschme
vim.cmd.colorscheme("monoglow")

vim.api.nvim_set_hl(0, 'LineNr', { fg = '#2b2b2b', bg = 'none', blend = 0 })
vim.api.nvim_set_hl(0, 'StatusCol', { fg = '#2b2b2b', bg = '#80401a', blend = 0 })
vim.api.nvim_set_hl(0, 'Normal', { fg = '#c0c0c1', bg = 'none' })
vim.api.nvim_set_hl(0, 'CursorLine', { fg = 'none', bg = 'none', blend = 5 })
-- vim.api.nvim_set_hl(0, 'CursorLine', { fg = 'none', bg = 'none'})
vim.api.nvim_set_hl(0, 'CursorLineNr', { fg = '#ff6000', bg = '#80401a' })
vim.api.nvim_set_hl(0, 'Visual', { fg = '#2b2b2b', bg = '#1bfd9c' })
-- vim.api.nvim_set_hl(0, 'MiniStatusLineModeNormal', { fg = '#ff6000', bg = '#80401a' })
vim.api.nvim_set_hl(0, 'NoiceCmdLinePopupBorder', { fg = '#ff6000', bg = 'none' })
vim.api.nvim_set_hl(0, 'SnacksPickerListCursorLine', { fg = '#ff6000', bg = '#80401a' })
vim.api.nvim_set_hl(0, 'WhichKey', { fg = '#ff6000', bg = 'none' })
vim.api.nvim_set_hl(0, 'SnacksPickerTitle', { fg = '#ff6000', bg = 'none' })
vim.api.nvim_set_hl(0, 'FloatBorder', { fg = '#ff6000', bg = 'none' })
vim.api.nvim_set_hl(0, 'VertSplit', { fg = '#80401a', bg = 'none' })
vim.api.nvim_set_hl(0, 'Special', { fg = '#ff6000', bg = 'none' })
vim.api.nvim_set_hl(0, 'SnacksPickerBoxBorder', { fg = '#ff6000', bg = 'none' })
vim.api.nvim_set_hl(0, 'NoiceScrollbar', { fg = 'none', bg = 'white' })
vim.api.nvim_set_hl(0, 'NoiceScrollbarThumb', { fg = 'none', bg = 'white' })
vim.api.nvim_set_hl(0, 'PmenuSbar', { fg = 'none', bg = 'none' })
vim.api.nvim_set_hl(0, 'PmenuThumb', { fg = 'none', bg = 'none' })
vim.api.nvim_set_hl(0, 'MasonHighlightBlock', { fg = '#ff6000', bg = '#80401a' })
vim.api.nvim_set_hl(0, 'MasonHighlightBlockBold', { fg = '#ff6000', bg = '#80401a' })
vim.api.nvim_set_hl(0, 'MasonHeaderSecondary', { fg = '#ff6000', bg = '#80401a' })
vim.api.nvim_set_hl(0, 'IblIndent', { fg = '#80401a' })
vim.api.nvim_set_hl(0, 'SnacksPickerDirectory', { fg = '#ff6000', bg = 'none' })
vim.api.nvim_set_hl(0, 'Comment', { fg = '#80401a', bg = 'none' })
vim.api.nvim_set_hl(0, 'CursorColumn', { fg = 'none', bg = 'none' })
-- vim.api.nvim_set_hl(0, 'Cursor', { fg = '#ff6000', bg = '#80401a' })
vim.api.nvim_set_hl(0, 'Insert', { fg = '#ff6000', bg = '#80401a' })
vim.api.nvim_set_hl(0, 'Whitespace', { fg = '#80401a', bg = 'none' })
vim.api.nvim_set_hl(0, 'Title', { fg = '#ff6000', bg = 'none' })
vim.api.nvim_set_hl(0, 'SignColumn', { fg = 'none', bg = '#80401a' })
vim.api.nvim_set_hl(0, 'StatusLineNC', { fg = 'none', bg = '#2b2b2b' })
vim.api.nvim_set_hl(0, 'StatusColumnBorder', { fg = '#ff6000', bg = '#2b2b2b' })
vim.api.nvim_set_hl(0, 'NoiceCursor', { fg = '#ff6000', bg = '#2b2b2b' })
vim.api.nvim_set_hl(0, 'NoiceFormatConfirmDefault', { fg = '#ff6000', bg = '#2b2b2b' })
vim.api.nvim_set_hl(0, 'SnacksPickerPrompt', { fg = '#ff6000', bg = '#2b2b2b' })
vim.api.nvim_set_hl(0, 'SnacksPickerListCursorLine', { fg = '#2b2b2b', bg = '#80401a' })
vim.api.nvim_set_hl(0, 'SnacksTitle', { fg = '#ff6000', bg = 'none' })
vim.api.nvim_set_hl(0, 'SnacksPickerCol', { fg = '#ff6000', bg = 'none' })
vim.api.nvim_set_hl(0, 'BarsBorder', { fg = '#ff6000', bg = 'none' })
vim.api.nvim_set_hl(0, 'BarsCursorLineNr', { fg = '#2b2b2b', bg = '#ff6000' })
vim.api.nvim_set_hl(0, 'Shadow10', { fg = '#2b2b2b', bg = '#e05806' })
vim.api.nvim_set_hl(0, 'Shadow9', { fg = '#2b2b2b', bg = '#c4510c' })
vim.api.nvim_set_hl(0, 'Shadow8', { fg = '#2b2b2b', bg = '#9d4714' })
vim.api.nvim_set_hl(0, 'Shadow7', { fg = '#2b2b2b', bg = '#80401a' })
vim.api.nvim_set_hl(0, 'Shadow6', { fg = '#2b2b2b', bg = '#643920' })
vim.api.nvim_set_hl(0, 'Shadow5', { fg = '#2b2b2b', bg = '#4e3424' })
vim.api.nvim_set_hl(0, 'Shadow4', { fg = '#2b2b2b', bg = '#473226' })
vim.api.nvim_set_hl(0, 'Shadow3', { fg = '#2b2b2b', bg = '#413127' })
vim.api.nvim_set_hl(0, 'Shadow2', { fg = '#2b2b2b', bg = '#3b2f28' })
vim.api.nvim_set_hl(0, 'Shadow1', { fg = '#2b2b2b', bg = '#362e29' })
vim.api.nvim_set_hl(0, 'Shadow0', { fg = 'none', bg = 'none' })
vim.api.nvim_set_hl(0, 'BorderShadow10', {fg = '#ff6000', bg = '#ff6000' })
vim.api.nvim_set_hl(0, 'BorderShadow9', { fg = '#ff6000', bg = '#c4510c' })
vim.api.nvim_set_hl(0, 'BorderShadow8', { fg = '#ff6000', bg = '#9d4714' })
vim.api.nvim_set_hl(0, 'BorderShadow7', { fg = '#ff6000', bg = '#80401a' })
vim.api.nvim_set_hl(0, 'BorderShadow6', { fg = '#ff6000', bg = '#643920' })
vim.api.nvim_set_hl(0, 'BorderShadow5', { fg = '#ff6000', bg = '#4e3424' })
vim.api.nvim_set_hl(0, 'BorderShadow4', { fg = '#ff6000', bg = '#473226' })
vim.api.nvim_set_hl(0, 'BorderShadow3', { fg = '#ff6000', bg = '#413127' })
vim.api.nvim_set_hl(0, 'BorderShadow2', { fg = '#ff6000', bg = '#3b2f28' })
vim.api.nvim_set_hl(0, 'BorderShadow1', { fg = '#ff6000', bg = '#362e29' })
vim.api.nvim_set_hl(0, 'BorderShadow0', { fg = '#ff6000', bg = 'none' })
vim.api.nvim_set_hl(0, 'SnacksPicker', { bg = 'none', fg = 'none' })
vim.api.nvim_set_hl(0, 'MonoGlow', { fg = '#1bfd9c', bg = '#80401a' })
vim.api.nvim_set_hl(0, 'MonoGlowStatusColumnBorder', { fg = '#ff0000', bg = '#1bfd9c' })
vim.api.nvim_set_hl(0, 'GitSignsAdd', { fg = '#2b2b2b', bg = '#80401a' })
vim.api.nvim_set_hl(0, 'GitSignsChange', { fg = '#2b2b2b', bg = '#80401a' })
vim.api.nvim_set_hl(0, 'GitSignsDelete', { fg = '#2b2b2b', bg = '#80401a' })
